version: '3'
services:
  nbp:
   build: ./nbp
   ports:
   - "8080:8080"
  nbpdb:
   image: mysql
   environment:
      MYSQL_DATABASE: nbpdb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
   ports:
    - "3306:3306"
   restart: always